import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "Introduction",
      collapsible: false,
      items: [
        { type: "doc", id: "overview", label: "Overview" },
        { type: "doc", id: "features", label: "Features" },
        {
          type: "category",
          label: "Getting Started",
          link: { type: "doc", id: "quick-start/index" },
          items: [
            { type: "autogenerated", dirName: "quick-start" },
            { type: "autogenerated", dirName: "getting-started" },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Core Concepts",
      collapsible: false,
      items: [
        { type: "autogenerated", dirName: "concepts" },
        {
          type: "category",
          label: "Custom Resources",
          items: [{ type: "autogenerated", dirName: "custom-resources" }],
        },
      ],
    },
    {
      type: "category",
      label: "Usage",
      collapsible: false,
      items: [
        {
          type: "category",
          label: "Integrations",
          items: [{ type: "autogenerated", dirName: "integrations" }],
        },
        {
          type: "category",
          label: "Observability",
          items: [{ type: "autogenerated", dirName: "observability" }],
        },
        {
          type: "category",
          label: "Security",
          items: [{ type: "autogenerated", dirName: "security" }],
        },
      ],
    },
    {
      type: "category",
      label: "Scaling & Operations",
      items: [{ type: "autogenerated", dirName: "scaling" }],
    },
    {
      type: "category",
      label: "Advanced",
      items: [{ type: "autogenerated", dirName: "advanced" }],
    },
    {
      type: "category",
      label: "Examples",
      items: [{ type: "autogenerated", dirName: "examples" }],
    },
    {
      type: "category",
      label: "Reference",
      items: [{ type: "autogenerated", dirName: "reference" }],
    },
    {
      type: "category",
      label: "Support",
      collapsible: false,
      items: [{ type: "doc", id: "faq", label: "FAQ" }],
    },
  ],
};

export default sidebars;
