import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "Introduction",
      collapsible: false,
      items: [
        { type: "doc", id: "overview", label: "Overview" },
        { type: "doc", id: "features", label: "Features" },
        {
          type: "category",
          label: "Quick Start",
          link: { type: "doc", id: "quick-start/index" },
          items: [{ type: "autogenerated", dirName: "quick-start" }],
        },
      ],
    },
    {
      type: "category",
      label: "Core",
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "core" }],
    },
    {
      type: "category",
      label: "Tools & Connections",
      items: [{ type: "autogenerated", dirName: "tools" }],
    },
    {
      type: "category",
      label: "Orchestration",
      items: [{ type: "autogenerated", dirName: "orchestration" }],
    },
    {
      type: "category",
      label: "Safety & Governance",
      items: [{ type: "autogenerated", dirName: "safety" }],
    },
    {
      type: "category",
      label: "FinOps",
      items: [{ type: "autogenerated", dirName: "finops" }],
    },
    {
      type: "category",
      label: "Intelligence",
      items: [{ type: "autogenerated", dirName: "intelligence" }],
    },
    {
      type: "category",
      label: "Discovery & Routing",
      items: [{ type: "autogenerated", dirName: "discovery" }],
    },
    {
      type: "category",
      label: "Operations",
      items: [{ type: "autogenerated", dirName: "operations" }],
    },
    {
      type: "category",
      label: "Reference",
      items: [
        { type: "autogenerated", dirName: "reference" },
        {
          type: "category",
          label: "Examples",
          items: [{ type: "autogenerated", dirName: "examples" }],
        },
      ],
    },
    {
      type: "category",
      label: "Support",
      collapsible: false,
      items: [{ type: "doc", id: "faq", label: "FAQ" }],
    },
  ],
};

export default sidebars;
